apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: NodePort      # this service must be accessible from outside
  selector:
    app: webserver
  ports:
  - port: 80          # port of service
    targetPort: 80    # port of pod
    nodePort: 30001   # por of node
